import Head from 'next/head';
import Link from 'next/link';

function Layout({ title, children }) {
  return (
    <>
      <Head>
        /<title>{title ? title + ' - Amazon' : 'Amazon'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="#" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex items-center h-12 px-4 justify-between shadow-md">
            <Link href="/">
              <p className="text-lg font-bold">Amazon</p>
            </Link>
            <div className="space-x-4">
              <Link href="/cart">Cart</Link>
              <Link href="/Login">Login</Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center item-center shadow-inner">
          Footer
        </footer>
      </div>
    </>
  );
}

export default Layout;
